<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
    <line>
      <![CDATA[<a href='TEST-shouldFindText.png'>screenshot</a>]]>
    </line>
  </reporter-output>
  <suite name="Default suite" duration-ms="19247" started-at="2012-05-20T02:19:19Z" finished-at="2012-05-20T02:19:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="19247" started-at="2012-05-20T02:19:19Z" finished-at="2012-05-20T02:19:38Z">
      <class name="com.mini.tests.BookTest">
        <test-method status="PASS" signature="setUpBeforeSuite()[pri:0, instance:com.mini.tests.BookTest@f73c1]" name="setUpBeforeSuite" is-config="true" duration-ms="8" started-at="2012-05-20T02:19:19Z" finished-at="2012-05-20T02:19:19Z">
        </test-method>
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.mini.tests.BookTest@f73c1]" name="setUpBeforeClass" is-config="true" duration-ms="0" started-at="2012-05-20T02:19:19Z" finished-at="2012-05-20T02:19:19Z">
        </test-method>
        <test-method status="FAIL" signature="shouldFindText()[pri:0, instance:com.mini.tests.BookTest@f73c1]" name="shouldFindText" duration-ms="18783" started-at="2012-05-20T02:19:19Z" finished-at="2012-05-20T02:19:37Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected:<Selenium: Beginners Guide1> but was:<Selenium: Beginners Guide>]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected:<Selenium: Beginners Guide1> but was:<Selenium: Beginners Guide>
	at org.testng.Assert.fail(Assert.java:89)
	at org.testng.Assert.failNotEquals(Assert.java:489)
	at org.testng.Assert.assertEquals(Assert.java:118)
	at org.testng.Assert.assertEquals(Assert.java:171)
	at org.testng.Assert.assertEquals(Assert.java:181)
	at com.mini.AbstractPage.open(AbstractPage.java:78)
	at com.mini.tests.BookTest.shouldFindText(BookTest.java:12)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:691)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:883)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1208)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:758)
	at org.testng.TestRunner.run(TestRunner.java:613)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1137)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1062)
	at org.testng.TestNG.run(TestNG.java:974)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:109)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:202)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:173)
]]>
            </full-stacktrace>
          </exception>
        </test-method>
        <test-method status="PASS" signature="tearDownAfterSuite()[pri:0, instance:com.mini.tests.BookTest@f73c1]" name="tearDownAfterSuite" is-config="true" duration-ms="268" started-at="2012-05-20T02:19:38Z" finished-at="2012-05-20T02:19:38Z">
        </test-method>
      </class>
    </test>
  </suite>
</testng-results>
